---
- name: Demo rules with kafka as source
  hosts: all
  sources:
    - ansible.eda.kafka:
        host: servera.aap.example.com
        port: 9092
        topic: eda-topic

  rules:
    - name: Say Hello
      condition: event.message != ""
      action:
        run_job_template:
          name: say-what
          organization: "LDAP Organization"
