---
- name: Read messages from a kafka topic and act on them
  hosts: all
  sources:
    - name: kafka
        ansible.eda.kafka:
          host: servera.aap.example.com
          port: 9092
          topic: eda
          group_id:
  rules:
    - name: Say Hello
      condition: event.message == "Ansible is cool"
      action:
        run_job_template:
          name: say-what
          organization: "LDAP Organization"
          job_args:
            extra_vars:
              message: from eda
