---
- name: Demo rules with kafka as source
  hosts: all
  sources:
    - name: kafka
      ansible.eda.kafka:
        host: servera.aap.example.com
        port: 9092
        topic: eda-topic
        group_id: eda-group
  rules:
    - name: Check for hello message
      condition: event.message == "hello"
      action:
        debug:

    - name: Say Hello
      condition: event.message == "Ansible is cool"
      action:
        run_job_template:
          name: say-what
          organization: "LDAP Organization"
